### ISSUE TITLE
Integer power base^exponent sample 27 incorrect for exponent==0

### ISSUE THREAD

**Issue by willwray** [BuildIt-lang/buildit#1]
buildit/samples/sample27.cpp
buildit.pdf paper, Fig. 7, top of page 4;
 
```
constexpr
int power(int base, int exponent) {
 int res = 1, x = base;       
 while (exponent > 1) {            //  while (exponent > 0) {            
   if (exponent % 2 == 1)       
     res = res * x;      
   x = x * x;           
   exponent = exponent / 2;
 }                 
 return res * x;                   //  return res;                   
}                

static_assert( power(2,0) == 1 );  // FAIL
static_assert( power(2,1) == 2 );
static_assert( power(2,2) == 4 );
```

As they say in Yorkshire; "Owt to the nowt is one".
Apologies for the OCD pedantry; I know it's just a sample...
Enjoying the read; interesting stuff. Thanks for putting this out here.

**Comment by AjayBrahmakshatriya** [comment]
Thanks a lot for pointing out this bug. Even though this is just a sample, you pointing out the issue came just in time as I am submitting the camera ready version of the paper. 

I will fix this right away in both the paper and the repo.

Also thanks for your interest in the project.
