### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by bftjoe** [BuildIt-lang/buildit#68]
Please add: mkdir build
to the documentation, or else make silently does nothing.

Also, it is unclear how to actually compile and run the emitted code. The examples seem to output something that can't be input into a C compiler. This is strange for a library which claims to be easy to use.

**Comment by AjayBrahmakshatriya** [comment]
Hi @bftjoe, 
Thanks for your interest in BuildIt. The Makefile itself has steps to create the appropriate directories. I think the only difference might be that the build system it written for GNU-make and not just make. I will update the instructions in the README to reflect that. 

Thanks for pointing it out
